LOAD DATA LOCAL INFILE 'custinput.txt' INTO TABLE customer (orgID, firstname, lastname, address, city, state, postalcode, phonenumber);
LOAD DATA LOCAL INFILE 'sellerinput.txt' INTO TABLE seller (orgID, firstname, lastname, familyname, sellergroupID);
LOAD DATA LOCAL INFILE 'sginput.txt' INTO TABLE sellergroup (orgID, name, active);
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-Trinity") where sellergroupID = 1000;
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-NoGrade") where sellergroupID = 1001;
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-music") where sellergroupID = 1002;
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-No Grade") where sellergroupID = 1003;
update seller set sellergroupID = (select id from sellergroup where name = "Care-a-Lot-No Grade") where sellergroupID = 1004;
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-11") where sellergroupID = 1005;
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-10") where sellergroupID = 1006;
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-9") where sellergroupID = 1007;
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-8") where sellergroupID = 1008;
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-7") where sellergroupID = 1009;
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-6") where sellergroupID = 1010;
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-5") where sellergroupID = 1011;
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-4") where sellergroupID = 1012;
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-3") where sellergroupID = 1013;
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-2") where sellergroupID = 1014;
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-1") where sellergroupID = 1015;
update seller set sellergroupID = (select id from sellergroup where name = "Trinity-K") where sellergroupID = 1016;
