name: Build PlantSale.war
run-name: ${{ github.actor }} is building PlantSale.war 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Build the WAR file
        run: |
          ant -f build.xml clean dist
      - run: echo "🍏 This job's status is ${{ job.status }}."
